version: "3.1"

services:

  rabbitmq:
    image: rabbitmq:3
    ports:
      - 5672:5672
      - 15672:15672

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
volumes:
  kafka_data:
    driver: local
